project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add_entry, name="add_entry"),
    path("wiki/<str:title>", views.entry_page, name="entry_page"),
    path("edit/<str:title>", views.edit_entry, name="edit_entry"),
    path("random_page", views.random_page, name="random_page")
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/views.py
import random

from django import forms
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from . import util


class NewEntryForm(forms.Form):
    """Form used for submiting new entry.
    """

    title = forms.CharField(label="Title")
    content =  forms.CharField(label="", widget=forms.Textarea())


def index(request: HttpRequest) -> HttpResponse:
    """View representing index page. If no query parameter 'q',
    lists all available entries. If 'q' parameter specified returns
    result from search_entry function.
    """

    query_str = request.GET.get('q', None)
    
    if query_str is not None:
        return search_entry(request, query_str)
    
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })


def entry_page(request: HttpRequest, title: str) -> HttpResponse:
    """Returns 'title' entry page. If no such entry, returns 404
    Not Found.
    """

    # sanitized_title = re.sub('_', ' ', title)
    entry_file = util.get_entry(title)
    
    if entry_file is None:
        return render(request, 'encyclopedia/not_found.html', status=404)
    
    html = util.markdown_to_html(entry_file)
    return render(request, "encyclopedia/entry.html", {
        "entry_title": title,
        "entry_body": html
    })


def search_entry(request: HttpRequest, query_str: str) -> HttpResponse:
    """Searches through entries. If exect match exists redirects to that page, else
    renders all entries that contain 'query_str' as substring in their title.
    """

    entries = util.list_entries()
    # if there is an exact match, redirect to that entry page
    if query_str in entries:
        return HttpResponseRedirect(reverse('wiki:entry_page', args=[query_str]))
    
    # otherwise list all entries that have query string as substring
    else:
        candidates = [e for e in entries if e.lower().find(query_str.lower()) != -1]
        return render(request, "encyclopedia/index.html", {
            "query_str": query_str,
            "entries": candidates
        })


def add_entry(request: HttpRequest) -> HttpResponse:
    """If method is GET renders an empty form for creating new
    wiki page. If method is POST and no entry with specified
    title already exists, stores new entry. If an entry with
    given title already exists returns 400 Bad Request response
    and form filled with data that was tried to be submitted
    """

    if request.method == "POST":
        entry_form = NewEntryForm(request.POST)
        
        if entry_form.is_valid():
            title = entry_form.cleaned_data['title']
            
            # if entry with this title already exists, render filled form with an error message
            # return appropriate 'Bad Request' status
            if util.exists_entry(title) is True:
                return render(request, 'encyclopedia/add.html', {
                    "form": entry_form,
                    "existing_title": True
                }, status=400)
            
            # otherwise save the entry
            util.save_entry(title, entry_form.cleaned_data['content'])
            
            # redirect to the newly created page
            return HttpResponseRedirect(reverse('wiki:entry_page', args=[title]))

    # if method GET, return empty form
    return render(request, "encyclopedia/add.html", {
        "form": NewEntryForm()
    })

def edit_entry(request: HttpRequest, title: str) -> HttpResponse:
    """When method is GET, fetches 'title' entry for editing. If method
    is POST, stores edited content of 'title' entry and redirects to that
    entry page.
    """

    if not util.exists_entry(title):
        return render(request, 'encyclopedia/not_found.html', status=404)

    if request.method == 'POST':
        content = request.POST['content']
        util.save_entry(title, content)

        return HttpResponseRedirect(reverse('wiki:entry_page', args=[title]))

    
    content = util.get_entry(title)
    return render(request, 'encyclopedia/edit.html', {
        "entry_title": title,
        "entry_content": content
    })

def random_page(request: HttpRequest) -> HttpResponse:
    """ Redirects to a random entry page
    """
    entries = util.list_entries()
    entry = entries[random.randrange(0, len(entries))]

    return HttpResponseRedirect(reverse('wiki:entry_page', args=[entry]))

project1/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - Add New Entry
{% endblock %}

{% block body %}
{% if existing_title is not None and existing_title %}
<h4 style="color: red;">No two entries can have same title!</h4>
{% endif %}
<div class="row">
    <div class="col-12">
        <form method="POST" action="{% url 'wiki:add_entry' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    {{ form }}
                </div>
            </div>
            <div class="row justify-content-start">
                <div class="col-3">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
Encyclopedia - Edit {{entry_title}}
{% endblock %}

{% block body %}
<h2>{{entry_title}}</h2>
<div class="row">
    <div class="col-12">
        <form action="{% url 'wiki:edit_entry' entry_title %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <textarea name="content">{{entry_content}}</textarea>
                </div>
            </div>
            <div class="row justify-content-start">
                <div class="col-3">
                    <input type="submit" value="Save changes">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Encyclopedia - {{entry_title}}
{% endblock %}

{% block body %}
    <a href="{% url 'wiki:edit_entry' entry_title %}" class="float-right mr-5 mt-4">Edit this entry</a>
    {{ entry_body|safe }}
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if query_str is None %}
        Encyclopedia
    
    {% else %}
        Encyclopedia - Search Results
    
    {% endif %}
{% endblock %}

{% block body %}
    
        {% if query_str is None %}

        <h1>All Pages</h1>
        
        {% else %}
        
        <h2>Search results for '{{query_str}}'</h2>
        
        {% endif %}
    
    
    <ul>
        {% for entry in entries %}
            <li>
            <a href="{% url 'wiki:entry_page' entry %}">{{ entry }}</a>
            </li>
            {% empty %}
            <li>No content...</li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}">
                    <input class="search" type="text" name="q" autocomplete="off" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add_entry' %}">Create New Page</a>
                </div>
                <div>
                   <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Encyclopedia - 404 Not Found
{% endblock %}

{% block body %}
    <h1>404 Not Found</h1>
{% endblock %}